# Generated by Django 5.1.15 on 2026-05-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(default='Mon Église', max_length=200, verbose_name="Nom de l'église")),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('default_currency', models.CharField(default='CDF', max_length=8, verbose_name='Devise par défaut')),
            ],
            options={
                'verbose_name': "Profil de l'église",
                'verbose_name_plural': "Profil de l'église",
            },
        ),
    ]
