# Generated by Django 5.1.15 on 2026-05-21 22:37

import apps.treasury.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('principale', 'Caisse principale'), ('secondaire', 'Caisse secondaire'), ('projet', 'Projet'), ('mission', 'Mission'), ('departement', 'Département')], default='principale', max_length=12, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('currency', models.CharField(default=apps.treasury.models.default_currency, max_length=8, verbose_name='Devise')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="Solde d'ouverture")),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Solde actuel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'offrande",
                'verbose_name_plural': "Types d'offrande",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaisseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('role', models.CharField(choices=[('caissier', 'Caissier'), ('responsable', 'Responsable'), ('auditeur', 'Auditeur')], default='caissier', max_length=12, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='treasury.caisse', verbose_name='Caisse')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_assignments', to='workers.worker', verbose_name='Ouvrier')),
            ],
            options={
                'verbose_name': 'Assignation de caisse',
                'verbose_name_plural': 'Assignations de caisse',
                'ordering': ['-created_at'],
                'unique_together': {('caisse', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], default='in', max_length=3, verbose_name='Sens')),
                ('category', models.CharField(choices=[('tithe', 'Dîme'), ('offering', 'Offrande'), ('donation', 'Don'), ('expense', 'Dépense'), ('transfer', 'Transfert'), ('other', 'Autre')], default='offering', max_length=12, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency', models.CharField(blank=True, max_length=8, verbose_name='Devise')),
                ('date', models.DateField(verbose_name='Date')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Libellé')),
                ('contributor_name', models.CharField(blank=True, max_length=160, verbose_name='Contributeur (nom libre)')),
                ('status', models.CharField(choices=[('validated', 'Validée'), ('pending', 'En attente'), ('cancelled', 'Annulée')], default='validated', max_length=10, verbose_name='Statut')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='treasury.caisse', verbose_name='Caisse')),
                ('contributor_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='workers.worker', verbose_name='Contributeur (ouvrier)')),
                ('offering_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='treasury.offeringtype', verbose_name="Type d'offrande")),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['category', 'direction'], name='treasury_tr_categor_7c620f_idx'), models.Index(fields=['date'], name='treasury_tr_date_c878fb_idx')],
            },
        ),
    ]
