# Generated by Django 5.1.15 on 2026-05-21 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=200, verbose_name='Acteur (libellé)')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('custom', 'Action')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(blank=True, max_length=40, verbose_name='Module')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Navigateur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx'), models.Index(fields=['model_name'], name='audit_audit_model_n_515731_idx')],
            },
        ),
    ]
