# Generated by Django 5.1.15 on 2026-05-21 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to='workers.worker', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='function',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='departments.department', verbose_name='Département'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('department', 'name')},
        ),
    ]
